name: flutter_practice
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  after_layout: ^1.2.0
  get: ^4.6.5
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.2
  flutter_bloc: ^8.1.3
  floor: ^1.4.2
  floor_generator: ^1.4.2
  email_validator: ^2.1.17
  shared_preferences: ^2.2.0
  loading_indicator: ^3.1.1
  dio: ^5.3.2
  path_provider: ^2.1.0
  audioplayers: ^4.1.0
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.4
  injectable: ^2.3.0
  injectable_generator: ^2.4.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.3
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/default_user_icon.png

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700