// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUIvqwZQwZZbMOvMwplR72JcwONQUB9Js',
    appId: '1:166438575787:web:4a05c6fc5073943f6d21ee',
    messagingSenderId: '166438575787',
    projectId: 'flutterpractice-9b3e2',
    authDomain: 'flutterpractice-9b3e2.firebaseapp.com',
    storageBucket: 'flutterpractice-9b3e2.appspot.com',
    measurementId: 'G-MV7FS2NMC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2E2W9qtvMRmAAWTTSZ_10JNRk3aqhNpw',
    appId: '1:166438575787:android:159c64c9b174a0e56d21ee',
    messagingSenderId: '166438575787',
    projectId: 'flutterpractice-9b3e2',
    storageBucket: 'flutterpractice-9b3e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqcrqwFCX9sOLwmbxk_7NQubhNyAmRFRI',
    appId: '1:166438575787:ios:ac8cacf48fbcd6626d21ee',
    messagingSenderId: '166438575787',
    projectId: 'flutterpractice-9b3e2',
    storageBucket: 'flutterpractice-9b3e2.appspot.com',
    iosBundleId: 'com.example.flutterPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqcrqwFCX9sOLwmbxk_7NQubhNyAmRFRI',
    appId: '1:166438575787:ios:999b774a5639b4d16d21ee',
    messagingSenderId: '166438575787',
    projectId: 'flutterpractice-9b3e2',
    storageBucket: 'flutterpractice-9b3e2.appspot.com',
    iosBundleId: 'com.example.flutterPractice.RunnerTests',
  );
}
